# 5. 데이터 확인

In [2]:
import pandas as pd
df= pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
0     채치수  북산고  197   90   85  100  95  85      Python
1     정대만  북산고  184   40   35   50  55  25        Java
2     송태섭  북산고  168   80   75   70  80  75  Javascript
3     서태웅  북산고  187   40   60   70  75  80         NaN
4     강백호  북산고  188   15   20   10  35  10         NaN
5     변덕규  능남고  202   80  100   95  85  80           C
6     황태산  능남고  188   55   65   45  40  35      PYTHON
7     윤대협  능남고  190  100   85   90  95  95          C#

## DataFrame 확인
계산 가능한 데이터에 대해 Column 별로 데이터의 갯수, 평균, 표준편차, 최소/최대값 등의 정보를 보여줌

In [5]:
df.describe() # 계산을 할 수 있는 열에 대해서만 계산이 된다. (숫자형 데이터)

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [7]:
df.info() # column 별 데이터 타입과 null 값이 있는지 확인할 수 있다.

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 708.0 bytes

In [8]:
df.head() # 상위 5개 데이터 확인

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
0     채치수  북산고  197  90  85  100  95  85      Python
1     정대만  북산고  184  40  35   50  55  25        Java
2     송태섭  북산고  168  80  75   70  80  75  Javascript
3     서태웅  북산고  187  40  60   70  75  80         NaN
4     강백호  북산고  188  15  20   10  35  10         NaN

In [9]:
df.head(7) # 상위 7개 데이터 확인

       이름   학교    키  국어   영어   수학  과학  사회        SW특기
지원번호
0     채치수  북산고  197  90   85  100  95  85      Python
1     정대만  북산고  184  40   35   50  55  25        Java
2     송태섭  북산고  168  80   75   70  80  75  Javascript
3     서태웅  북산고  187  40   60   70  75  80         NaN
4     강백호  북산고  188  15   20   10  35  10         NaN
5     변덕규  능남고  202  80  100   95  85  80           C
6     황태산  능남고  188  55   65   45  40  35      PYTHON

In [12]:
df.tail() # 하위 5개 데이터 확인

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
3     서태웅  북산고  187   40   60  70  75  80     NaN
4     강백호  북산고  188   15   20  10  35  10     NaN
5     변덕규  능남고  202   80  100  95  85  80       C
6     황태산  능남고  188   55   65  45  40  35  PYTHON
7     윤대협  능남고  190  100   85  90  95  95      C#

In [13]:
df.tail(3) # 하위 3개 데이터 확인

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
5     변덕규  능남고  202   80  100  95  85  80       C
6     황태산  능남고  188   55   65  45  40  35  PYTHON
7     윤대협  능남고  190  100   85  90  95  95      C#

In [14]:
df.values

array([['채치수', '북산고', 197, 90, 85, 100, 95, 85, 'Python'],
       ['정대만', '북산고', 184, 40, 35, 50, 55, 25, 'Java'],
       ['송태섭', '북산고', 168, 80, 75, 70, 80, 75, 'Javascript'],
       ['서태웅', '북산고', 187, 40, 60, 70, 75, 80, nan],
       ['강백호', '북산고', 188, 15, 20, 10, 35, 10, nan],
       ['변덕규', '능남고', 202, 80, 100, 95, 85, 80, 'C'],
       ['황태산', '능남고', 188, 55, 65, 45, 40, 35, 'PYTHON'],
       ['윤대협', '능남고', 190, 100, 85, 90, 95, 95, 'C#']], dtype=object)

In [15]:
df.index

RangeIndex(start=0, stop=8, step=1, name='지원번호')

In [16]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [17]:
df.shape # 행과 열의 개수 확인

(8, 9)

In [18]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
0     채치수  북산고  197   90   85  100  95  85      Python
1     정대만  북산고  184   40   35   50  55  25        Java
2     송태섭  북산고  168   80   75   70  80  75  Javascript
3     서태웅  북산고  187   40   60   70  75  80         NaN
4     강백호  북산고  188   15   20   10  35  10         NaN
5     변덕규  능남고  202   80  100   95  85  80           C
6     황태산  능남고  188   55   65   45  40  35      PYTHON
7     윤대협  능남고  190  100   85   90  95  95          C#

## series 확인

In [ ]:
df['키'].min()

NameError: name 'df' is not defined

In [20]:
df['키'].max()

np.int64(202)

In [22]:
df['키'].describe()

count      8.000000
mean     188.000000
std        9.985704
min      168.000000
25%      186.250000
50%      188.000000
75%      191.750000
max      202.000000
Name: 키, dtype: float64

In [24]:
df['키'].nlargest(3)

지원번호
5    202
0    197
7    190
Name: 키, dtype: int64

In [33]:
df['키'].mean()

np.float64(188.0)

In [27]:
df['키'].sum()

np.int64(1504)

In [28]:
df['SW특기'].count() # SW특기 열에서 데이터가 있는 개수 확인

np.int64(6)

In [30]:
df['학교'].unique() # 학교 열에서 중복되지 않는 데이터 확인

<StringArray>
['북산고', '능남고']
Length: 2, dtype: str

In [32]:
df['학교'].nunique() # 학교 열에서 중복되지 않는 데이터의 개수 확인

2

In [10]:
import pandas as pd
df=pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [11]:
df[:5].columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [12]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [13]:
df.columns[:5]

Index(['이름', '학교', '키', '국어', '영어'], dtype='str')