# 09. 데이터 선택 (조건)

In [1]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [2]:
df['키'] >= 185 # 학생들의 키가 185 이상인지 여부를 True, False로 반환

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [31]:
filt = (df['키'] >= 185) 
df[filt]

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
4번    서태웅  북산고  187   40   60   70  75  80     NaN
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
7번    황태산  능남고  188   55   65   45  40  35  PYTHON
8번    윤대협  능남고  190  100   85   90  95  95      C#

In [32]:
df['키'] >= 185

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [4]:
df[~filt] # 키가 185 미만인 학생들만 출력

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    정대만  북산고  184  40  35  50  55  25        Java
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [6]:
df[df['키'] >= 185]

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
4번    서태웅  북산고  187   40   60   70  75  80     NaN
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
7번    황태산  능남고  188   55   65   45  40  35  PYTHON
8번    윤대협  능남고  190  100   85   90  95  95      C#

In [8]:
df.loc[df['키'] >= 185, '수학'] # 키가 185 이상인 학생들의 수학 점수

지원번호
1번    100
4번     70
5번     10
6번     95
7번     45
8번     90
Name: 수학, dtype: int64

In [9]:
df.loc[df['키'] >= 185, ['이름', '수학', '과학']] # 키가 185 이상인 학생들의 이름, 수학, 과학 점수

       이름   수학  과학
지원번호
1번    채치수  100  95
4번    서태웅   70  75
5번    강백호   10  35
6번    변덕규   95  85
7번    황태산   45  40
8번    윤대협   90  95

## 다양한  조건

### & 그리고

In [13]:
df.loc[(df['키'] >= 185) & (df['학교'] == '북산고') ] # 키가 185 이상이면서 학교가 북산고인 학생들의 데이터

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85  Python
4번    서태웅  북산고  187  40  60   70  75  80     NaN
5번    강백호  북산고  188  15  20   10  35  10     NaN

### |또는

In [14]:
df.loc[(df['키'] < 170) | (df['키'] > 200)] # 키가 170 미만이거나 200 초과인 학생들의 데이터]

       이름   학교    키  국어   영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80   75  70  80  75  Javascript
6번    변덕규  능남고  202  80  100  95  85  80           C

### str 함수

In [16]:
filt = df['이름'].str.startswith('송') # 송씨 성을 가진 사람
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [17]:
filt= df['이름'].str.contains('태') # 이름에 '태' 글자가 포함된 사람
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80  75  70  80  75  Javascript
4번    서태웅  북산고  187  40  60  70  75  80         NaN
7번    황태산  능남고  188  55  65  45  40  35      PYTHON

In [18]:
df[~filt] #이름에 '태' 글자가 포함되지 않은 사람

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
2번    정대만  북산고  184   40   35   50  55  25    Java
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
8번    윤대협  능남고  190  100   85   90  95  95      C#

In [24]:
langs = ["Python", "Java"]
filt = df['SW특기'].isin(langs) # SW특기가 python이거나 Java인 사람
df[filt]

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85  Python
2번    정대만  북산고  184  40  35   50  55  25    Java

In [20]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [27]:
# 대문자인 Python이 포함된 사람을 포함시키려면
langs = ["python", "java"]
filt = df['SW특기'].str.lower().isin(langs) # SW특기의 모든 글자를 소문자로 바꿔서 비교
df[filt]

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85  Python
2번    정대만  북산고  184  40  35   50  55  25    Java
7번    황태산  능남고  188  55  65   45  40  35  PYTHON

In [29]:
# Java가 포함된 사람을 포함시키려면
filt = df['SW특기'].str.contains('Java')
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    정대만  북산고  184  40  35  50  55  25        Java
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [30]:
df['SW특기'].str.lower().isin(langs)

지원번호
1번     True
2번     True
3번    False
4번    False
5번    False
6번    False
7번     True
8번    False
Name: SW특기, dtype: bool

In [37]:
df['SW특기'].str.contains('Java', na=True)

지원번호
1번    False
2번     True
3번     True
4번     True
5번     True
6번    False
7번    False
8번    False
Name: SW특기, dtype: bool

In [35]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

### STR 함수

In [7]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [8]:
filt = df['이름'].str.startswith('송') # 이름이 송씨인 사람
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [9]:
filt = df['이름'].str.contains('태') # 이름에 '태' 글자가 포함된 사람
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80  75  70  80  75  Javascript
4번    서태웅  북산고  187  40  60  70  75  80         NaN
7번    황태산  능남고  188  55  65  45  40  35      PYTHON

In [10]:
df[~filt] # 이름에 '태' 글자가 포함되지 않은 사람

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
2번    정대만  북산고  184   40   35   50  55  25    Java
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
8번    윤대협  능남고  190  100   85   90  95  95      C#