# 결측지
비어 있는 데이터

In [1]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## 데이터 채우기 fillna

In [2]:
df.fillna('') # NaN 값을 빈 문자열로 대체

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [3]:
df.fillna('없음')

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80          없음
5번    강백호  북산고  188   15   20   10  35  10          없음
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [5]:
import numpy as np
df['학교'] = np.nan # 학교 데이터 전체를 NAN으로 채움
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80         NaN
5번    강백호 NaN  188   15   20   10  35  10         NaN
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [22]:
df.fillna('모름')

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  모름  197   90   85  100  95  85      Python
2번    정대만  모름  184   40   35   50  55  25        Java
3번    송태섭  모름  168   80   75   70  80  75  Javascript
4번    서태웅  모름  187   40   60   70  75  80          모름
5번    강백호  모름  188   15   20   10  35  10          모름
6번    변덕규  모름  202   80  100   95  85  80           C
7번    황태산  모름  188   55   65   45  40  35      PYTHON
8번    윤대협  모름  190  100   85   90  95  95          C#

In [23]:
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80         NaN
5번    강백호 NaN  188   15   20   10  35  10         NaN
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [27]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')

In [29]:
df.fillna('모름', inplace=True)  # 원본에 적용
df                       # 확인

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80          모름
5번    강백호  북산고  188   15   20   10  35  10          모름
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [30]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80          모름
5번    강백호  북산고  188   15   20   10  35  10          모름
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [31]:
import numpy as np
df['학교'] = np.nan # 학교 데이터 전체를 NAN으로 채움
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80          모름
5번    강백호 NaN  188   15   20   10  35  10          모름
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [35]:
df.fillna('모름', inplace=True) # 원본 데이터에 바로 적용, 학교는 float으로 인식하여 오류가 발생    
df

TypeError: Invalid value '모름' for dtype 'float64'

In [36]:
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80          모름
5번    강백호 NaN  188   15   20   10  35  10          모름
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [ ]:
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  모름  197   90   85  100  95  85      Python
2번    정대만  모름  184   40   35   50  55  25        Java
3번    송태섭  모름  168   80   75   70  80  75  Javascript
4번    서태웅  모름  187   40   60   70  75  80          모름
5번    강백호  모름  188   15   20   10  35  10          모름
6번    변덕규  모름  202   80  100   95  85  80           C
7번    황태산  모름  188   55   65   45  40  35      PYTHON
8번    윤대협  모름  190  100   85   90  95  95          C#

In [41]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [42]:
df['SW특기'].fillna('확인 중') # SW특기 열의 결측치만 '확인 중'으로 대체

지원번호
1번        Python
2번          Java
3번    Javascript
4번          확인 중
5번          확인 중
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [43]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [51]:
df['SW특기'] = df['SW특기'].fillna('확인 중')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80        확인 중
5번    강백호  북산고  188   15   20   10  35  10        확인 중
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [52]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80        확인 중
5번    강백호  북산고  188   15   20   10  35  10        확인 중
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## 데이터 제외하기 Dropna

In [55]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [56]:
df.dropna() # 결측치가 있는 행 제거

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [57]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

- axis : index or columns  
- how : any or all

In [58]:
df.dropna(axis='index', how='any') # NAN이 하나라도 있는 행 제거

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [59]:
df.dropna(axis='columns') # NAN이 하나라도 있는 열 제거

       이름   학교    키   국어   영어   수학  과학  사회
지원번호
1번    채치수  북산고  197   90   85  100  95  85
2번    정대만  북산고  184   40   35   50  55  25
3번    송태섭  북산고  168   80   75   70  80  75
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80
7번    황태산  능남고  188   55   65   45  40  35
8번    윤대협  능남고  190  100   85   90  95  95

In [60]:
df['학교'] = np.nan
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80         NaN
5번    강백호 NaN  188   15   20   10  35  10         NaN
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [61]:
df.dropna(axis='columns', how= 'all') # 데이터 전체가 NAN 경우에만 Column 삭제

       이름    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  197   90   85  100  95  85      Python
2번    정대만  184   40   35   50  55  25        Java
3번    송태섭  168   80   75   70  80  75  Javascript
4번    서태웅  187   40   60   70  75  80         NaN
5번    강백호  188   15   20   10  35  10         NaN
6번    변덕규  202   80  100   95  85  80           C
7번    황태산  188   55   65   45  40  35      PYTHON
8번    윤대협  190  100   85   90  95  95          C#