# 함수 적용

In [2]:
import pandas as pd

df=pd.read_excel("score.xlsx", index_col="지원번호")
# `키` 열은 처음에 숫자형인지 확인
print('dtype of 키 before any changes ->', df['키'].dtype)
df

dtype of 키 before any changes -> int64

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [ ]:
# 키 뒤에 cm을 붙이는 역할
def add_cm(height):
    return str(height) + 'cm'

# 적용 전 dtype
print('before apply:', df['키'].dtype)

df['키'] = df['키'].apply(add_cm)

# 적용 후 dtype
print('after apply :', df['키'].dtype)
df

       이름   학교      키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197cm   90   85  100  95  85      Python
2번    정대만  북산고  184cm   40   35   50  55  25        Java
3번    송태섭  북산고  168cm   80   75   70  80  75  Javascript
4번    서태웅  북산고  187cm   40   60   70  75  80         NaN
5번    강백호  북산고  188cm   15   20   10  35  10         NaN
6번    변덕규  능남고  202cm   80  100   95  85  80           C
7번    황태산  능남고  188cm   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190cm  100   85   90  95  95          C#

In [ ]:
# 3. 함수로 처리하면서 원본 유지하기

# 열 자체를 변형하지 않고 보기용 Series를 생성
formatted_heights = df['키'].apply(lambda h: f"{h}cm")
formatted_heights.head()

# 필요하다면 새 컬럼에 할당하되 기존 컬럼은 변경하지 않음
# df['키_보기용'] = formatted_heights

In [11]:
df['키'].dtypes

dtype('int64')

In [12]:
formatted_heights = df['키'].apply(lambda h: f"{h}cm")
formatted_heights.head()

지원번호
1번    197cm
2번    184cm
3번    168cm
4번    187cm
5번    188cm
Name: 키, dtype: str

In [20]:
pip install jinja2

Collecting jinja2
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting MarkupSafe>=2.0 (from jinja2)
  Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Installing collected packages: MarkupSafe, jinja2

   -------------------- ------------------- 1/2 [jinja2]
   ---------------------------------------- 2/2 [jinja2]

Successfully installed MarkupSafe-3.0.3 jinja2-3.1.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
# 출력 단계에서만 포맷 적용
df.style.format({'키': '{:.0f}cm'})

In [4]:
def Capitalize(lang):
    if pd.notnull(lang): # NAN이 아닌지
        return lang.capitalize() # 첫 글자는 대문자로, 나머지는 소문자로
    return lang

df['SW특기'] = df['SW특기'].apply(Capitalize)
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#